"""add requisition models

Revision ID: 9e5d02a48c13
Revises: d2e3f4a5b6c7
Create Date: 2026-07-09 10:25:37.109340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5d02a48c13'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisitions',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('admin_comment', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegramuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitions_status'), 'requisitions', ['status'], unique=False)
    op.create_index(op.f('ix_requisitions_telegram_user_id'), 'requisitions', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_requisitions_type'), 'requisitions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisitions_type'), table_name='requisitions')
    op.drop_index(op.f('ix_requisitions_telegram_user_id'), table_name='requisitions')
    op.drop_index(op.f('ix_requisitions_status'), table_name='requisitions')
    op.drop_table('requisitions')
    # ### end Alembic commands ###
